[project]
name = "costbot"
version = "0.1.0"
requires-python = ">=3.9"

dependencies = [
    "aiohttp>=3.13.3",
    "fastapi>=0.128.8",
    "python-dotenv>=1.2.1",
    "tzdata>=2025.3",
    "uvicorn>=0.39.0",
]
